### ISSUE TITLE
how can I get the vocoder file when using mel 

### ISSUE THREAD

**Issue by Cescfangs** [CODEJIN/MLPSinger#1]
https://github.com/CODEJIN/MLPSinger/blob/404af5bdd092fbf91f615043bd50457c0fd80c23/Train.py#L155-L156
Thanks for sharing, BTW.

**Comment by CODEJIN** [comment]
Hi,  Cescfangs,

Unfortunately, the vocoder is trained with a private data. A colleague was shared the private dataset personally, and it cannot be shared. However, the code in this repository does not require any vocoder if you set up hyperparameters to train with spectrograms. And when I tested, the performance difference between spectrogram and mel was not significant. I recommend that you proceed with the spectrogram training until you configure your own vocoder with personal data in the future.

Best regards,

Heejo
